### ISSUE TITLE
Define more asset/link attributes & define a core set of types

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#139]
There hasn't been a clear standard of what additional attributes / field names to include in STAC Items. We have enough real world examples that we should be able to set down more than just the href and rel link.

- [x] add type attribute for assets #175 
- [x] add type attribute for links (assets do mime_type, wfs links do just 'type' but use the mime type - need to decide which to do, and revisit name for assets too)
- [x] add 'title' attribute for links and assets. #263 
- [x] Define common types #180 (perhaps expand that PR to cover links too)
- [x] update examples for these.

We also should define a set of core types that are commonly used. Is it geotiff / geotif / cog, etc. See #54 as well, as it has some discussion of this. The list should start as just a best practice recommendation, and keep it open to evolve. But align initial tooling around those types.

**Comment by m-mohr** [comment]
Having a (required?) title would help humans to explore the catalogs more easily as you can only guess from rel and href what the referenced entity is about. I'd like to reference two related issues here for the discussion: https://github.com/mojodna/stac-browser/issues/2 and https://github.com/mojodna/stac-browser/issues/4

Having a title (and a type) would also comply to RFC5988.

**Comment by cholmes** [comment]
I don't think title should be required, but I do think we should have it speced.

**Comment by m-mohr** [comment]
Yes, I fully agree.

Should we change that in the assets, too? There it is already specified as 'name'.
