### ISSUE TITLE
Remove polygon / multi-polygon restriction

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#193]
We decided to make it so any geometry can be used at STAC sprint 3. 

See additional discussion at #44 and #177 

This is a tracking issue, to make sure we fully update everything.

- [x] Update json spec (done in #177) 
- [x] Update json schema (done in #177)
- [ ] Check OpenAPI definitions and make sure they're in line. Related to #131

**Comment by cholmes** [comment]
@hgs-trutherford / @jasongilman / @scisco - could one of you check the openapi definitions for this?

**Comment by hgs-truthe01** [comment]
@cholmes I'd like to merge #201 first, but I can open a PR for this. @m-mohr had suggested some links to use, for geometry, so I'll try taking that approach.

**Comment by m-mohr** [comment]
Merged, go for it, @hgs-truthe01 👍
